server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: k1:9092,k2:9092,k3:9092
    producer:
      # 重试次数
      retries: 3
      # 批量发送的消息数量
      batch-size: 16384
      # 32MB的批处理缓冲区
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      #value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: com.ley.serializer.LeyKafkaAvroSerializer
    consumer:
      # 默认消费者组
      group-id: group-1
      # 重试消费者组，相同group的不同consumer多次消费同一个topic
      retry-group-id: __retry__
      # 最早未被消费的offset
      auto-offset-reset: earliest
      # 批量一次最大拉取数据量
      max-poll-records: 1000
      # 自动提交
      auto-commit-interval: 1000
      enable-auto-commit: true
      # 应用需要处理消息的时间ms
      max-poll-interval-ms: 10000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.ley.serializer.LeyKafkaAvroDeserializer
    listener:
      # consumer并发处理的线程数(启动几个线程委托给 KafkaMessageListenerContainer)
      concurrency: 2
      # 轮询消费者时使用的超时时间 ms
      poll-timeout: 3000
topicName:
  topic1: test
