
#spring:
#  redis:
#    database: 0
#    host: 10.67.36.163
#    port: 6380
#    password: d8FMee6Tg8VpLH

auth:
  url: http://localhost:8080
  username: test
  password: test

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true




