spring:
  application:
    name: have-fun
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.175.101:3306/rabbit_records?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: 123456
  cloud:
    stream:
      rabbit:
        bindings:
          output-r-direct-q1:
            producer:
              declareExchange: false
              routingKeyExpression: '''exchange1-direct-q1-routing-key'''
          input-r-direct-q1:
            consumer:
              bindQueue: false
              declareExchange: false
              queueNameGroupOnly: true
              acknowledgeMode: manual
              exchangeType: direct
              bindingRoutingKey: exchange1-direct-q1-routing-key
      bindings:
        output-r-direct-q1:
          binder: my-rabbit-4
          destination: exchange-1
          exchangeType: direct
          mymq: rabbit
          mytype: output
          mq-log-table: t_sent
        input-r-direct-q1:
          binder: my-rabbit-4
          destination: exchange-1
          group: direct-q1
          mymq: rabbit
          mytype: input
          mq-log-table: t_sent
          consumer:
            max-attempts: 1

      binders:
        my-rabbit-4:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.175.101
                port: 5672
                username: user
                password: password
                virtual-host: vh-1

